swagger: '2.0'
info:
  title: ftfty
  version: '1.0'
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /api/v1/videos:
    get:
      summary: GET Videos
      tags: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/video'
          examples: {}
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/403'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/404'
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/422'
      operationId: get-api-v1-videos
      parameters:
        - type: string
          in: header
          name: Content-Type
          description: application/json
        - type: string
          in: header
          name: Authorization
          description: JWT Token
  '/api/v1/videos/{id}':
    get:
      summary: GET Video
      tags: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/video'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/403'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/404'
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/422'
      operationId: 'get-api-v1-videos-:id'
      description: get video by id
      parameters:
        - type: string
          in: header
          name: Content-Type
          description: application/json
        - type: string
          in: header
          description: JWT Token
          name: Authorization
    parameters:
      - type: string
        name: id
        in: path
        required: true
  /api/v1/videos/upload:
    post:
      summary: POST Upload Video
      operationId: post-api-v1-videos-upload
      responses:
        '200':
          description: OK
          headers: {}
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/400'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/403'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/404'
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/422'
        '':
          description: ''
      parameters:
        - type: string
          in: header
          name: Content-Type
          description: |
            application/json
        - type: string
          in: header
          name: Authorization
          description: JWT Token
        - in: formData
          type: string
          name: start_time
          description: start trim time sec
        - in: formData
          type: string
          name: end_time
          description: end trim time sec
        - in: formData
          type: file
          name: "[{\"key\":\"attachment\",\"description\":\"\",\"type\":\"file\",\"enabled\":true,\"value\":[\"/Users/admin/Desktop/199-solid-open-closed-principle.mp4\"],\"warning\":\"This file isn't in your working directory. Teammates you share this request with won't be able to use this file. To make collaboration easier you can setup your working directory in Settings.\"}]"
          description: "attachment file ['mp4]"
          required: true
      description: Upload video
    parameters: []
  '/api/v1/videos/{id}/failed/retry':
    parameters:
      - type: string
        name: id
        in: path
        required: true
    post:
      summary: POST Retry Upload Video
      operationId: post-api-v1-videos-id-failed-retry
      responses:
        '200':
          description: OK
          headers: {}
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/403'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/404'
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/422'
      parameters:
        - type: string
          in: header
          name: Content-Type
          description: |
            application/json
        - type: string
          in: header
          name: Authorization
          description: JWT Token
        - in: formData
          type: file
          name: attachment
          description: "attachment file ['mp4]"
          required: true
  /api/v1/authenticate:
    post:
      summary: POST Auth
      operationId: post-api-v1-authenticate
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/401'
      parameters:
        - type: string
          in: header
          name: Content-Type
          description: application/json
        - type: string
          in: header
          name: email
          description: email login
        - type: integer
          in: header
          name: password
          description: password
definitions:
  '400':
    title: 400
    type: object
    properties:
      message:
        type: string
        description: "\"attachment\": \n    [\"can't be blank\"]\n    [\"is invalid\"]\n    [\"less_than 200 mb\"]\n    "
  '401':
    title: 401
    type: object
    properties:
      message:
        type: string
        description: Invalid credentials
  '403':
    title: 403
    type: object
    properties:
      message:
        type: string
        description: Forbidden
  '404':
    title: 404
    type: object
    properties:
      message:
        type: string
        description: |-
          Document not found for class Video with attributes {:id=>"your_
          id"
  '422':
    title: 422
    type: object
    properties:
      mwssage:
        type: string
        description: Missing token
  user:
    title: user
    type: object
    properties:
      id:
        type: string
  video:
    title: video
    type: object
    properties:
      id:
        type: string
      state:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
      duration:
        type: integer
      url:
        type: string
