development:
  adapter: 'mongoid'
  clients:
    default:
      database: video_upload_development
      hosts:
        - localhost:27017
      options:
        allow_dynamic_fields: false
        identity_map_enabled: true
        include_root_in_json: true
        include_type_for_serialization: true
        user: root
        password: root
        auth_source: admin
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      database: video_upload_test
      hosts:
        - localhost:27017
      options:
        user: root
        password: root
        auth_source: admin
        read:
          mode: :primary
        max_pool_size: 1
  options:
    raise_not_found_error: false
