development:
  clients:
    default:
      database: video_upload_development
      hosts:
        - localhost:27017
      options:
        user: root
        password: root
        auth_source: admin
  options:
test:
  clients:
    default:
      database: video_upload_test
      hosts:
        - localhost:27017
      options:
        user: root
        password: root
        auth_source: admin
        read:
          mode: :primary
        max_pool_size: 1
